---
name: CI

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
