---
name: CI

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: requirements
        runs: pip install -r requirements.txt
      - name: code style
        runs: pycodestyle app.py
      - name: sast
        runs: bandit app.py